[package]
name = "shimmy"
version = "0.1.0"
authors = ["Ivan Velichko <iximiuz@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
nix = "0.15.0"

[[bin]]
name = "shimmy"
path = "src/shimmy.rs"

[[bin]]
name = "pipe"
path = "src/pipe.rs"

